GET http://localhost:8080/users
Accept: application/json

###

POST http://localhost:8080/users/auth/login
Content-Type: application/json

{
    "username": "user01",
    "password": "password"
}

###

POST http://localhost:8080/users/auth/signup
Content-Type: application/json

{
    "username": "user01",
    "password": "password",
    "email": "someuser@gmail.com",
    "phone": "+6500000000",
    "countryOfResidences": "Japan",
    "dob": "2017-01-02",
    "authorities": "USER"
}